LAST_ID = '/home/dhistory/apps/trovenewsbot/src/last_id.txt'
LOCK_FILE = '/home/dhistory/apps/trovenewsbot/src/locked.txt'
LOG_FILE = '/home/dhistory/apps/trovenewsbot/src/errors.txt'
LAST_URL = '/home/dhistory/apps/trovenewsbot/src/last_url.txt'
LAST_DPLA = '/home/dhistory/apps/trovenewsbot/src/last_dpla.txt'
LAST_DNZ = '/home/dhistory/apps/trovenewsbot/src/last_dnz.txt'
TEMP_IMAGE = '/home/dhistory/apps/trovenewsbot/src/temp_image.jpg'
